### PR TITLE
chore: update nodejs version

### PR DESCRIPTION
**Pull request by mikesposito**
Fixes [#16613](https://github.com/MetaMask/metamask-extension/issues/16613)

### CODE REVIEW

**Review by legobeat — CHANGES_REQUESTED** [review]
The CI matrix in `workflows/build-test.yml` still runs v12.

**Comment by mikesposito** [comment]
> The CI matrix in `workflows/build-test.yml` still runs v12.

I removed the v12 from the build matrix. 

@legobeat @adonesky1  Currently, the extension is using Node `v16`, and we might want to update it soon to the latest LTS (v18): do you think it would make more sense to update this package to `v16` or directly to `v18`?

**Comment by mcmire** [comment]
Just a thought: We can add support for other Node versions and set the development version of Node (`.nvmrc`) however we want, but from an `engines` perspective, we may want to keep the minimum version of Node at v14 as it hasn't hit end-of-life yet. This follows what our [module template](https://github.com/MetaMask/metamask-module-template/blob/0d9154886718bbd4a4fae9e2974517344933ac42/package.json#L56) is doing.

**Review by legobeat — APPROVED** [review]

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
